server:
  port: 8082
spring:
  application:
    name: creditinfo
  datasource:
    username: czals757
    password: czals757
    url: jdbc:oracle:thin:@localhost:1521:orcl
    driver-class-name: oracle.jdbc.driver.OracleDriver
    #默认就是HikarCP连接池。 性能很好
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 150
      minimum-idle: 10
  jpa:
    hibernate:
      # 更新或者创建数据表结构
      ddl-auto: update
      naming:
        # 开启后JPA创建的表名 和 字段名 不带下划线。
        # SpringData JPA 使用的默认命名策略是： ImprovedNamingStrategy 。用下划线转换驼峰名
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

#Eureka client相关
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册消息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka01.com:9001/eureka,http://eureka02.com:9002/eureka
  instance:
    instance-id: creditinfo
    prefer-ip-address: true
#actuator 监控相关
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: info,beans,env,mappings #开启那些监听
      base-path: /actuator  #访问监控的路径名
  endpoint:
    health:
      show-details: always

# fegin默认关闭hystrix服务 OpenFeign其实就已经集成了Hystrix
feign:
  hystrix:
    enabled: true