server:
  port: 8083
spring:
  application:
    name: creditinfo
  datasource:
    username: czals757
    password: czals757
    url: jdbc:oracle:thin:@localhost:1521:orcl
    driver-class-name: oracle.jdbc.driver.OracleDriver
    #默认就是HikarCP连接池。 性能很好
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 150
      minimum-idle: 10
  jpa:
    hibernate:
      # 更新或者创建数据表结构
      ddl-auto: update
      naming:
        # 开启后JPA创建的表名 和 字段名 不带下划线。
        # SpringData JPA 使用的默认命名策略是： ImprovedNamingStrategy 。用下划线转换驼峰名
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

#Eureka client相关
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册消息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka01.com:9001/eureka,http://eureka02.com:9002/eureka
  instance:
    instance-id: creditinfo01
    prefer-ip-address: true
#actuator 监控相关
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*" #开启那些监听
      base-path: /actuator  #访问监控的路径名
  endpoint:
    health:
      show-details: always

# fegin默认关闭hystrix服务 OpenFeign其实就已经集成了Hystrix
feign:
  hystrix:
    enabled: true

hystrix:
  dashboard:
    proxy-stream-allow-list: "*"
  # 线程池核心线程数
  threadpool:
    default:
      coreSize: 15
      # 最大排队长度。默认-1，使用SynchronousQueue。其他值则使用 LinkedBlockingQueue。如果要从-1换成其他值则需重启，即该值不能动态调整，若要动态调整，需要使用到下边这个配置
      maxQueueSize: 1000
      #即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝，默认值5
      # 排队线程数量阈值，默认为5，达到时拒绝，如果配置了该选项，队列的大小是该队列
      # 注意上面的值如果设置为-1 则此值没用。 本质的目的是为了动态调整。  比如现在的配置。 可以支持同时并发15个，等待队列20个。 超出的走拒绝策略
      queueSizeRejectionThreshold: 20